name: ambiente_fase_5_deep_learning
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - seaborn
  - matplotlib
  - numpy
  - scikit-learn
  - openpyxl
  - tqdm
  - ipykernel
  - ipywidgets
  - opencv
  - nltk
  - gensim
  - spacy
  - pip
  - pip:
    - gdown
    - tensorflow
    - wordcloud
    - minisom
    - imageio
    - Pillow
    - pt-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.7.0/pt_core_news_sm-3.7.0-py3-none-any.whl